import { NextRequest, NextResponse } from "next/server";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { normalizeNbaSeasonLabel } from "@/lib/nba/players-db";

export const maxDuration = 300;

const DEFAULT_SEASON = normalizeNbaSeasonLabel(
  process.env.APISPORTS_NBA_SEASON ?? "2025",
);
const DEFAULT_GAMES_LEAGUE = (() => {
  const raw = process.env.APISPORTS_NBA_LEAGUE_ID ?? "standard";
  const value = String(raw).trim().toLowerCase();
  if (!value || value === "nba" || value === "12") return "standard";
  return value;
})();
const DEFAULT_TIMEZONE = "America/Toronto";
const DEFAULT_CONCURRENCY = 8;
const MAX_CONCURRENCY = 16;
const DEFAULT_TIMEOUT_MS = 25000;
const FINISHED_STATUSES = new Set(["FT", "AOT", "AET", "AWD", "WO"]);
const DEFAULT_TARGET_MODE = "played";
const DEFAULT_ROTATION_PER_TEAM = 10;
const MAX_ROTATION_PER_TEAM = 15;
const DEFAULT_ROTATION_MIN_GP = 1;
const MAX_ROTATION_MIN_GP = 10;
const UPSTREAM_NBA_API_BASE =
  process.env.APISPORTS_NBA_URL || "https://v2.nba.api-sports.io";
const UPSTREAM_API_KEY = process.env.APISPORTS_KEY;

type InternalGamesPayload = {
  ok?: boolean;
  response?: Array<{
    id?: number | string | null;
    date?: string | null;
    timestamp?: number | null;
    status?: { short?: string | null; long?: string | null } | null;
    teams?: {
      home?: { id?: number | null; name?: string | null; code?: string | null };
      away?: { id?: number | null; name?: string | null; code?: string | null };
    } | null;
  }>;
};
type InternalGame = NonNullable<InternalGamesPayload["response"]>[number];

type RefreshResult = {
  playerId: number;
  ok: boolean;
  games?: number;
  maxDate?: string | null;
  maxDateToronto?: string | null;
  status?: number;
  error?: string;
};

type RosterRefreshResult = {
  attempted: boolean;
  ok: boolean;
  status: number | null;
  count: number | null;
  dbUpserted: number | null;
  error: string | null;
};

type UpstreamPlayerStat = {
  player?: { id?: number | string | null };
  team?: {
    id?: number | string | null;
    name?: string | null;
    code?: string | null;
  } | null;
  min?: string | number | null;
  points?: number | string | null;
  assists?: number | string | null;
  totReb?: number | string | null;
  fgm?: number | string | null;
  fga?: number | string | null;
  fgp?: number | string | null;
  tpm?: number | string | null;
  fta?: number | string | null;
  ftm?: number | string | null;
  ftp?: number | string | null;
  tpa?: number | string | null;
  tpp?: number | string | null;
};

type PlayedLogRow = {
  player_id: number;
  season: string;
  game_id: number;
  date: string | null;
  team_id: number | null;
  team_code: string | null;
  team_name: string | null;
  opponent_team_id: number | null;
  opponent_team_code: string | null;
  opponent_team_name: string | null;
  home_away: "home" | "away" | "unknown";
  result: "W" | "L" | "NA";
  score: string | null;
  score_home: number | null;
  score_away: number | null;
  points: number | null;
  rebounds: number | null;
  assists: number | null;
  minutes: number | null;
  field_goals_made: number | null;
  field_goals_attempted: number | null;
  field_goal_pct: number | null;
  three_points_made: number | null;
  three_points_attempted: number | null;
  three_point_pct: number | null;
  free_throws_made: number | null;
  free_throws_attempted: number | null;
  free_throw_pct: number | null;
  is_preseason: boolean | null;
  league_id: number | null;
  status_short: string | null;
};

let logsTableInit: Promise<void> | null = null;

async function ensureLogsTable() {
  if (logsTableInit) return logsTableInit;
  logsTableInit = (async () => {
    await prisma.$executeRawUnsafe(`
      create table if not exists nba_player_game_logs (
        id bigint generated by default as identity primary key,
        player_id integer not null,
        season text not null,
        game_id integer not null,
        date timestamptz,
        team_id integer,
        team_code text,
        team_name text,
        opponent_team_id integer,
        opponent_team_code text,
        opponent_team_name text,
        home_away text,
        result text,
        score text,
        score_home integer,
        score_away integer,
        points numeric,
        rebounds numeric,
        assists numeric,
        minutes numeric,
        field_goals_made numeric,
        field_goals_attempted numeric,
        field_goal_pct numeric,
        three_points_made numeric,
        three_points_attempted numeric,
        three_point_pct numeric,
        free_throws_made numeric,
        free_throws_attempted numeric,
        free_throw_pct numeric,
        is_preseason boolean,
        league_id integer,
        status_short text,
        created_at timestamptz default now(),
        updated_at timestamptz default now(),
        unique (player_id, season, game_id)
      );
    `);
    await prisma.$executeRawUnsafe(`
      create index if not exists nba_player_game_logs_player_season_idx
      on nba_player_game_logs (player_id, season, date desc);
    `);
  })();
  return logsTableInit;
}

function parsePositiveInt(
  raw: string | null,
  fallback: number,
  maxValue: number,
): number {
  const n = Number(raw ?? fallback);
  if (!Number.isFinite(n) || n <= 0) return fallback;
  return Math.min(Math.floor(n), maxValue);
}

function toNumberSafe(value: unknown): number | null {
  const n = Number(value);
  return Number.isFinite(n) ? n : null;
}

function parseMinutes(value: unknown): number | null {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  if (typeof value !== "string") return null;
  const raw = value.trim();
  if (!raw) return null;
  if (raw.includes(":")) {
    const [m, s] = raw.split(":");
    const mm = Number(m);
    const ss = Number(s);
    if (Number.isFinite(mm) && Number.isFinite(ss)) return mm + ss / 60;
  }
  const n = Number(raw);
  return Number.isFinite(n) ? n : null;
}

function toText(value: unknown): string | null {
  if (typeof value === "string") return value;
  if (typeof value === "number") return String(value);
  return null;
}

function buildPlayedRowsForGame(
  game: InternalGame,
  stats: UpstreamPlayerStat[],
  seasonForLogs: string,
): PlayedLogRow[] {
  const gameId = Number(game?.id ?? NaN);
  if (!Number.isFinite(gameId) || gameId <= 0) return [];

  const gameDate =
    typeof game?.date === "string" && Number.isFinite(Date.parse(game.date))
      ? new Date(game.date).toISOString()
      : null;
  const homeId = toNumberSafe(game?.teams?.home?.id);
  const awayId = toNumberSafe(game?.teams?.away?.id);
  const homeName = toText(game?.teams?.home?.name);
  const awayName = toText(game?.teams?.away?.name);
  const homeCode = toText(game?.teams?.home?.code);
  const awayCode = toText(game?.teams?.away?.code);
  const homeScore = toNumberSafe((game as any)?.scores?.home?.total);
  const awayScore = toNumberSafe((game as any)?.scores?.away?.total);
  const score =
    homeScore !== null && awayScore !== null ? `${homeScore}-${awayScore}` : null;
  const leagueId = toNumberSafe((game as any)?.league?.id);
  const statusShort = toText((game as any)?.status?.short);

  const rows: PlayedLogRow[] = [];
  for (const stat of stats) {
    const playerId = toNumberSafe(stat?.player?.id);
    if (!playerId || playerId <= 0) continue;
    const minutes = parseMinutes(stat?.min);
    const hasAction =
      (minutes !== null && minutes > 0) ||
      [stat?.points, stat?.assists, stat?.totReb, stat?.fga, stat?.fta, stat?.tpa]
        .map((v) => toNumberSafe(v))
        .some((v) => v !== null && v > 0);
    if (!hasAction) continue;

    const teamId = toNumberSafe(stat?.team?.id);
    const teamName = toText(stat?.team?.name);
    const teamCode = toText(stat?.team?.code);
    let homeAway: "home" | "away" | "unknown" = "unknown";
    if (teamId !== null && homeId !== null && teamId === homeId) homeAway = "home";
    if (teamId !== null && awayId !== null && teamId === awayId) homeAway = "away";

    const opponentTeamId =
      homeAway === "home" ? awayId : homeAway === "away" ? homeId : null;
    const opponentTeamName =
      homeAway === "home" ? awayName : homeAway === "away" ? homeName : null;
    const opponentTeamCode =
      homeAway === "home" ? awayCode : homeAway === "away" ? homeCode : null;

    let result: "W" | "L" | "NA" = "NA";
    if (
      homeAway !== "unknown" &&
      homeScore !== null &&
      awayScore !== null &&
      homeScore !== awayScore
    ) {
      const won =
        (homeAway === "home" && homeScore > awayScore) ||
        (homeAway === "away" && awayScore > homeScore);
      result = won ? "W" : "L";
    }

    rows.push({
      player_id: playerId,
      season: seasonForLogs,
      game_id: gameId,
      date: gameDate,
      team_id: teamId,
      team_code: teamCode,
      team_name: teamName,
      opponent_team_id: opponentTeamId,
      opponent_team_code: opponentTeamCode,
      opponent_team_name: opponentTeamName,
      home_away: homeAway,
      result,
      score,
      score_home: homeScore,
      score_away: awayScore,
      points: toNumberSafe(stat?.points),
      rebounds: toNumberSafe(stat?.totReb),
      assists: toNumberSafe(stat?.assists),
      minutes,
      field_goals_made: toNumberSafe(stat?.fgm),
      field_goals_attempted: toNumberSafe(stat?.fga),
      field_goal_pct: toNumberSafe(stat?.fgp),
      three_points_made: toNumberSafe(stat?.tpm),
      three_points_attempted: toNumberSafe(stat?.tpa),
      three_point_pct: toNumberSafe(stat?.tpp),
      free_throws_made: toNumberSafe(stat?.ftm),
      free_throws_attempted: toNumberSafe(stat?.fta),
      free_throw_pct: toNumberSafe(stat?.ftp),
      is_preseason: false,
      league_id: leagueId,
      status_short: statusShort,
    });
  }

  return rows;
}

async function upsertPlayedRows(rows: PlayedLogRow[]): Promise<void> {
  if (!rows.length) return;
  await ensureLogsTable();
  const nowIso = new Date().toISOString();
  const queries = rows.map((row) => prisma.$executeRaw`
    insert into nba_player_game_logs (
      player_id,
      season,
      game_id,
      date,
      team_id,
      team_code,
      team_name,
      opponent_team_id,
      opponent_team_code,
      opponent_team_name,
      home_away,
      result,
      score,
      score_home,
      score_away,
      points,
      rebounds,
      assists,
      minutes,
      field_goals_made,
      field_goals_attempted,
      field_goal_pct,
      three_points_made,
      three_points_attempted,
      three_point_pct,
      free_throws_made,
      free_throws_attempted,
      free_throw_pct,
      is_preseason,
      league_id,
      status_short,
      updated_at
    ) values (
      ${row.player_id},
      ${row.season},
      ${row.game_id},
      cast(${row.date} as timestamptz),
      ${row.team_id},
      ${row.team_code},
      ${row.team_name},
      ${row.opponent_team_id},
      ${row.opponent_team_code},
      ${row.opponent_team_name},
      ${row.home_away},
      ${row.result},
      ${row.score},
      ${row.score_home},
      ${row.score_away},
      ${row.points},
      ${row.rebounds},
      ${row.assists},
      ${row.minutes},
      ${row.field_goals_made},
      ${row.field_goals_attempted},
      ${row.field_goal_pct},
      ${row.three_points_made},
      ${row.three_points_attempted},
      ${row.three_point_pct},
      ${row.free_throws_made},
      ${row.free_throws_attempted},
      ${row.free_throw_pct},
      ${row.is_preseason},
      ${row.league_id},
      ${row.status_short},
      cast(${nowIso} as timestamptz)
    )
    on conflict (player_id, season, game_id)
    do update set
      date = coalesce(excluded.date, nba_player_game_logs.date),
      team_id = coalesce(excluded.team_id, nba_player_game_logs.team_id),
      team_code = coalesce(excluded.team_code, nba_player_game_logs.team_code),
      team_name = coalesce(excluded.team_name, nba_player_game_logs.team_name),
      opponent_team_id = coalesce(excluded.opponent_team_id, nba_player_game_logs.opponent_team_id),
      opponent_team_code = coalesce(excluded.opponent_team_code, nba_player_game_logs.opponent_team_code),
      opponent_team_name = coalesce(excluded.opponent_team_name, nba_player_game_logs.opponent_team_name),
      home_away = coalesce(excluded.home_away, nba_player_game_logs.home_away),
      result = coalesce(excluded.result, nba_player_game_logs.result),
      score = coalesce(excluded.score, nba_player_game_logs.score),
      score_home = coalesce(excluded.score_home, nba_player_game_logs.score_home),
      score_away = coalesce(excluded.score_away, nba_player_game_logs.score_away),
      points = coalesce(excluded.points, nba_player_game_logs.points),
      rebounds = coalesce(excluded.rebounds, nba_player_game_logs.rebounds),
      assists = coalesce(excluded.assists, nba_player_game_logs.assists),
      minutes = coalesce(excluded.minutes, nba_player_game_logs.minutes),
      field_goals_made = coalesce(excluded.field_goals_made, nba_player_game_logs.field_goals_made),
      field_goals_attempted = coalesce(excluded.field_goals_attempted, nba_player_game_logs.field_goals_attempted),
      field_goal_pct = coalesce(excluded.field_goal_pct, nba_player_game_logs.field_goal_pct),
      three_points_made = coalesce(excluded.three_points_made, nba_player_game_logs.three_points_made),
      three_points_attempted = coalesce(excluded.three_points_attempted, nba_player_game_logs.three_points_attempted),
      three_point_pct = coalesce(excluded.three_point_pct, nba_player_game_logs.three_point_pct),
      free_throws_made = coalesce(excluded.free_throws_made, nba_player_game_logs.free_throws_made),
      free_throws_attempted = coalesce(excluded.free_throws_attempted, nba_player_game_logs.free_throws_attempted),
      free_throw_pct = coalesce(excluded.free_throw_pct, nba_player_game_logs.free_throw_pct),
      is_preseason = coalesce(excluded.is_preseason, nba_player_game_logs.is_preseason),
      league_id = coalesce(excluded.league_id, nba_player_game_logs.league_id),
      status_short = coalesce(excluded.status_short, nba_player_game_logs.status_short),
      updated_at = excluded.updated_at
  `);
  await prisma.$transaction(queries);
}

function torontoYmd(date = new Date()): string {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: DEFAULT_TIMEZONE,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(date);
}

function addDaysYmd(ymd: string, days: number): string {
  const ts = Date.parse(`${ymd}T12:00:00Z`);
  if (!Number.isFinite(ts)) return ymd;
  const next = new Date(ts + days * 24 * 60 * 60 * 1000);
  const y = next.getUTCFullYear();
  const m = String(next.getUTCMonth() + 1).padStart(2, "0");
  const d = String(next.getUTCDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

function torontoYmdFromIso(raw: string | null): string | null {
  if (!raw) return null;
  const ts = Date.parse(raw);
  if (!Number.isFinite(ts)) return null;
  return torontoYmd(new Date(ts));
}

async function refreshPlayerSummary(
  origin: string,
  season: string,
  playerId: number,
  options?: { expectedDate?: string | null; strictDate?: boolean },
): Promise<RefreshResult> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), DEFAULT_TIMEOUT_MS);
  try {
    const url = new URL(`/api/nba/players/${playerId}/summary`, origin);
    url.searchParams.set("season", season);
    url.searchParams.set("refresh", "1");
    const res = await fetch(url.toString(), {
      cache: "no-store",
      signal: controller.signal,
    });
    if (!res.ok) return { playerId, ok: false, status: res.status };
    const payload = (await res.json().catch(() => null)) as
      | { summary?: { games?: unknown[] } }
      | null;
    const games = Array.isArray(payload?.summary?.games) ? payload.summary!.games! : [];
    const maxDate =
      games.length > 0
        ? games
            .map((g) =>
              typeof (g as { date?: unknown })?.date === "string"
                ? ((g as { date: string }).date as string)
                : null,
            )
            .find((d) => d && Number.isFinite(Date.parse(d))) ?? null
        : null;
    const maxDateToronto = torontoYmdFromIso(maxDate);
    if (options?.strictDate && options.expectedDate && maxDateToronto !== options.expectedDate) {
      return {
        playerId,
        ok: false,
        games: games.length,
        maxDate,
        maxDateToronto,
        error: "stale_after_refresh",
      };
    }
    return { playerId, ok: true, games: games.length, maxDate, maxDateToronto };
  } catch (err) {
    const abort =
      err instanceof DOMException
        ? err.name === "AbortError"
        : String(err).toLowerCase().includes("abort");
    return {
      playerId,
      ok: false,
      error: abort ? "timeout" : err instanceof Error ? err.message : String(err),
    };
  } finally {
    clearTimeout(timeout);
  }
}

async function syncPlayerTeamsFromLatestLogs(
  seasons: string[],
  playerIds: number[],
): Promise<{ updated: number }> {
  if (!playerIds.length || !seasons.length) return { updated: 0 };

  const rows = await prisma.$queryRaw<Array<{ player_id: number }>>(
    Prisma.sql`
      with latest_logs as (
        select distinct on (l.player_id)
          l.player_id,
          l.team_id,
          l.team_code,
          l.team_name
        from nba_player_game_logs l
        where l.season in (${Prisma.join(seasons.map((s) => Prisma.sql`${s}`))})
          and l.player_id in (${Prisma.join(playerIds.map((id) => Prisma.sql`${id}`))})
          and (
            l.team_id is not null
            or nullif(trim(coalesce(l.team_code, '')), '') is not null
          )
        order by l.player_id, l.date desc nulls last, l.game_id desc
      )
      update nba_players p
      set
        team_code = ll.team_code,
        team_name = coalesce(ll.team_name, p.team_name),
        updated_at = now()
      from latest_logs ll
      where p.season in (${Prisma.join(seasons.map((s) => Prisma.sql`${s}`))})
        and p.player_id = ll.player_id
        and (
          coalesce(p.team_code, '') is distinct from coalesce(ll.team_code, '')
          or coalesce(p.team_name, '') is distinct from coalesce(ll.team_name, '')
        )
      returning p.player_id
    `,
  );

  return { updated: rows.length };
}

function buildSeasonAliases(input: string): string[] {
  const raw = String(input ?? "").trim();
  if (!raw) return [];
  const normalized = normalizeNbaSeasonLabel(raw);
  const year = raw.match(/(\d{4})/)?.[1] ?? normalized.match(/(\d{4})/)?.[1] ?? null;
  const span = year ? `${year}-${Number(year) + 1}` : null;
  return Array.from(new Set([raw, normalized, year, span].filter(Boolean))) as string[];
}

export async function GET(req: NextRequest) {
  const cronSecret = process.env.CRON_SECRET;
  if (cronSecret) {
    const authHeader = req.headers.get("authorization") ?? "";
    const customHeader = req.headers.get("x-cron-secret") ?? "";
    const querySecret = req.nextUrl.searchParams.get("secret") ?? "";
    const valid =
      authHeader === `Bearer ${cronSecret}` ||
      customHeader === cronSecret ||
      querySecret === cronSecret;
    if (!valid) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
  }

  const season = normalizeNbaSeasonLabel(
    req.nextUrl.searchParams.get("season") ?? DEFAULT_SEASON,
  );
  const leagueParam = String(
    req.nextUrl.searchParams.get("league") ?? DEFAULT_GAMES_LEAGUE,
  )
    .trim()
    .toLowerCase();
  const gamesLeague =
    !leagueParam || leagueParam === "nba" || leagueParam === "12"
      ? "standard"
      : leagueParam;
  const seasonAliases = buildSeasonAliases(season);
  const date =
    req.nextUrl.searchParams.get("date") ?? addDaysYmd(torontoYmd(), -1);
  const concurrency = parsePositiveInt(
    req.nextUrl.searchParams.get("concurrency"),
    DEFAULT_CONCURRENCY,
    MAX_CONCURRENCY,
  );
  const maxPlayers = parsePositiveInt(
    req.nextUrl.searchParams.get("max"),
    5000,
    5000,
  );
  const targetModeRaw = String(
    req.nextUrl.searchParams.get("mode") ?? DEFAULT_TARGET_MODE,
  )
    .trim()
    .toLowerCase();
  const targetMode =
    targetModeRaw === "rotation"
      ? "rotation"
      : targetModeRaw === "played"
        ? "played"
        : "full";
  const rotationPerTeam = parsePositiveInt(
    req.nextUrl.searchParams.get("perTeam"),
    DEFAULT_ROTATION_PER_TEAM,
    MAX_ROTATION_PER_TEAM,
  );
  const rotationMinGp = parsePositiveInt(
    req.nextUrl.searchParams.get("minGp"),
    DEFAULT_ROTATION_MIN_GP,
    MAX_ROTATION_MIN_GP,
  );
  const dryRun = req.nextUrl.searchParams.get("dry") === "1";
  const includeDetails = req.nextUrl.searchParams.get("details") === "1";
  const refreshRoster = req.nextUrl.searchParams.get("refreshRoster") !== "0";
  const startedAt = Date.now();

  try {
    const gamesUrl = new URL("/api/nba/games", req.nextUrl.origin);
    gamesUrl.searchParams.set("date", date);
    gamesUrl.searchParams.set("season", season);
    gamesUrl.searchParams.set("league", gamesLeague);
    gamesUrl.searchParams.set("timezone", DEFAULT_TIMEZONE);

    const gamesRes = await fetch(gamesUrl.toString(), {
      cache: "no-store",
      signal: AbortSignal.timeout(20_000),
    });
    if (!gamesRes.ok) {
      return NextResponse.json(
        {
          ok: false,
          error: "Failed to load games for target date",
          status: gamesRes.status,
          date,
          season,
        },
        { status: 502 },
      );
    }

    const gamesPayload = (await gamesRes.json().catch(() => null)) as
      | InternalGamesPayload
      | null;
    const games = Array.isArray(gamesPayload?.response)
      ? gamesPayload!.response!
      : [];
    const finishedGames = games.filter((g) =>
      FINISHED_STATUSES.has(String(g?.status?.short ?? "").toUpperCase()),
    );
    const gamesForScope = finishedGames.length ? finishedGames : games;

    const teamIds = new Set<number>();
    const teamCodes = new Set<string>();
    for (const game of gamesForScope) {
      const homeId = Number(game?.teams?.home?.id ?? NaN);
      const awayId = Number(game?.teams?.away?.id ?? NaN);
      if (Number.isFinite(homeId) && homeId > 0) teamIds.add(homeId);
      if (Number.isFinite(awayId) && awayId > 0) teamIds.add(awayId);

      const homeCode = String(game?.teams?.home?.code ?? "")
        .trim()
        .toUpperCase();
      const awayCode = String(game?.teams?.away?.code ?? "")
        .trim()
        .toUpperCase();
      if (homeCode) teamCodes.add(homeCode);
      if (awayCode) teamCodes.add(awayCode);
    }
    const seasonYear = season.match(/(\d{4})/)?.[1] ?? season;
    const playedRowsAll: PlayedLogRow[] = [];
    const playedGameFetchFailures: Array<{ gameId: number; status?: number; error?: string }> =
      [];

    if (targetMode === "played") {
      if (!UPSTREAM_API_KEY) {
        return NextResponse.json(
          { ok: false, error: "Missing APISPORTS_KEY for played sync mode" },
          { status: 500 },
        );
      }
      for (const game of gamesForScope) {
        const gameId = Number(game?.id ?? NaN);
        if (!Number.isFinite(gameId) || gameId <= 0) continue;
        try {
          const url = new URL("/players/statistics", UPSTREAM_NBA_API_BASE);
          url.searchParams.set("game", String(gameId));
          url.searchParams.set("season", seasonYear);
          const res = await fetch(url.toString(), {
            headers: { "x-apisports-key": UPSTREAM_API_KEY },
            cache: "no-store",
            signal: AbortSignal.timeout(20_000),
          });
          if (!res.ok) {
            playedGameFetchFailures.push({ gameId, status: res.status });
            continue;
          }
          const payload = (await res.json().catch(() => null)) as
            | { response?: UpstreamPlayerStat[] }
            | null;
          const stats = Array.isArray(payload?.response) ? payload.response : [];
          playedRowsAll.push(...buildPlayedRowsForGame(game, stats, season));
        } catch (err) {
          playedGameFetchFailures.push({
            gameId,
            error: err instanceof Error ? err.message : String(err),
          });
        }
      }
    }

    const seasonSql = Prisma.join(seasonAliases.map((s) => Prisma.sql`${s}`));
    const collectTargetedPlayerIds = async (): Promise<number[]> => {
      const playerIds = new Set<number>();
      const addRows = (rows: Array<{ player_id: number }>) => {
        for (const row of rows) {
          const id = Number(row.player_id);
          if (Number.isFinite(id) && id > 0) playerIds.add(id);
        }
      };

      if (targetMode === "played") {
        for (const row of playedRowsAll) {
          if (row.player_id > 0) playerIds.add(row.player_id);
        }
      } else if (targetMode === "rotation" && teamIds.size > 0) {
        const ids = Array.from(teamIds.values());
        const rows = await prisma.$queryRaw<Array<{ player_id: number }>>`
          with base as (
            select
              l.team_id,
              l.player_id,
              l.minutes,
              row_number() over (
                partition by l.team_id, l.player_id
                order by l.date desc nulls last, l.game_id desc
              ) as rn
            from nba_player_game_logs l
            where l.season in (${seasonSql})
              and l.team_id in (${Prisma.join(ids)})
              and coalesce(l.is_preseason, false) = false
              and coalesce(l.minutes, 0) > 0
          ),
          agg as (
            select
              team_id,
              player_id,
              avg(minutes) filter (where rn <= 10) as avg_min_l10,
              count(*) filter (where rn <= 10) as gp_l10
            from base
            group by team_id, player_id
          ),
          ranked as (
            select
              team_id,
              player_id,
              row_number() over (
                partition by team_id
                order by coalesce(avg_min_l10, 0) desc, gp_l10 desc, player_id asc
              ) as rnk
            from agg
            where gp_l10 >= ${rotationMinGp}
          )
          select distinct player_id
          from ranked
          where rnk <= ${rotationPerTeam}
        `;
        addRows(rows);
      } else if (teamIds.size > 0) {
        const ids = Array.from(teamIds.values());
        const rows = await prisma.$queryRaw<Array<{ player_id: number }>>`
          select distinct player_id
          from nba_players
          where season in (${seasonSql})
            and team_id in (${Prisma.join(ids)})
        `;
        addRows(rows);
        if (teamCodes.size > 0) {
          const codes = Array.from(teamCodes.values());
          const codeRows = await prisma.$queryRaw<Array<{ player_id: number }>>`
            select distinct player_id
            from nba_players
            where season in (${seasonSql})
              and upper(coalesce(team_code, '')) in (${Prisma.join(codes.map((c) => Prisma.sql`${c}`))})
          `;
          addRows(codeRows);
        }
      }

      if (targetMode !== "played") {
        // Fallback safety for non-played modes: include players already logged on target date.
        const logRows = await prisma.$queryRaw<Array<{ player_id: number }>>`
          select distinct player_id
          from nba_player_game_logs
          where season in (${Prisma.join(seasonAliases.map((s) => Prisma.sql`${s}`))})
            and (date at time zone ${DEFAULT_TIMEZONE})::date = ${date}::date
        `;
        addRows(logRows);
      }

      return Array.from(playerIds.values()).slice(0, maxPlayers);
    };

    const allPlayerIds = await collectTargetedPlayerIds();
    if (dryRun) {
      return NextResponse.json({
        ok: true,
        mode: "dry-run",
        season,
        date,
        gamesFound: games.length,
        finishedGames: finishedGames.length,
        teamsFound: teamIds.size,
        playersTargeted: allPlayerIds.length,
        targetMode,
        rotationPerTeam,
        rotationMinGp,
        refreshRoster,
        durationMs: Date.now() - startedAt,
      });
    }

    let rosterRefreshResult: RosterRefreshResult = {
      attempted: false,
      ok: true,
      status: null,
      count: null,
      dbUpserted: null,
      error: null,
    };

    if (refreshRoster) {
      rosterRefreshResult.attempted = true;
      try {
        const syncUrl = new URL("/api/nba/sync-players-v2", req.nextUrl.origin);
        const syncRes = await fetch(syncUrl.toString(), {
          cache: "no-store",
          signal: AbortSignal.timeout(120_000),
        });
        const syncJson = (await syncRes.json().catch(() => null)) as
          | { ok?: boolean; count?: number; dbUpserted?: number; error?: string }
          | null;
        rosterRefreshResult = {
          attempted: true,
          ok: Boolean(syncRes.ok && syncJson?.ok),
          status: syncRes.status,
          count:
            typeof syncJson?.count === "number" && Number.isFinite(syncJson.count)
              ? syncJson.count
              : null,
          dbUpserted:
            typeof syncJson?.dbUpserted === "number" && Number.isFinite(syncJson.dbUpserted)
              ? syncJson.dbUpserted
              : null,
          error:
            syncRes.ok && syncJson?.ok
              ? null
              : (syncJson?.error ?? `sync-players-v2 failed (${syncRes.status})`),
        };
      } catch (err) {
        rosterRefreshResult = {
          attempted: true,
          ok: false,
          status: null,
          count: null,
          dbUpserted: null,
          error: err instanceof Error ? err.message : String(err),
        };
      }
    }
    const targetPlayerIds =
      refreshRoster && rosterRefreshResult.ok
        ? await collectTargetedPlayerIds()
        : allPlayerIds;

    let processed = 0;
    let success = 0;
    let failed = 0;
    const failedDetails: RefreshResult[] = [];
    const successPlayerIds: number[] = [];
    if (targetMode === "played") {
      const targetSet = new Set(targetPlayerIds);
      const dedupedRowMap = new Map<string, PlayedLogRow>();
      for (const row of playedRowsAll) {
        if (!targetSet.has(row.player_id)) continue;
        dedupedRowMap.set(`${row.player_id}:${row.game_id}`, row);
      }
      const rowsToUpsert = Array.from(dedupedRowMap.values());
      await upsertPlayedRows(rowsToUpsert);

      processed = targetPlayerIds.length;
      const successSet = new Set(rowsToUpsert.map((row) => row.player_id));
      success = successSet.size;
      failed = Math.max(0, processed - success);
      successPlayerIds.push(...Array.from(successSet.values()));

      if (includeDetails && failed > 0) {
        for (const playerId of targetPlayerIds) {
          if (successSet.has(playerId)) continue;
          if (failedDetails.length >= 250) break;
          failedDetails.push({
            playerId,
            ok: false,
            error: "missing_played_rows_for_player",
          });
        }
      }
    } else {
      for (let i = 0; i < targetPlayerIds.length; i += concurrency) {
        const slice = targetPlayerIds.slice(i, i + concurrency);
        const results = await Promise.all(
          slice.map((playerId) =>
            refreshPlayerSummary(req.nextUrl.origin, season, playerId, {
              strictDate: false,
              expectedDate: null,
            }),
          ),
        );
        processed += results.length;
        for (const result of results) {
          if (result.ok) {
            success += 1;
            successPlayerIds.push(result.playerId);
          } else {
            failed += 1;
            if (failedDetails.length < 250) failedDetails.push(result);
          }
        }
      }
    }

    const rosterSync = await syncPlayerTeamsFromLatestLogs(seasonAliases, successPlayerIds);

    const coverageRows = await prisma.$queryRaw<
      Array<{ players: number; max_date: string | null }>
    >`
      select
        count(distinct player_id)::int as players,
        max(date)::text as max_date
      from nba_player_game_logs
      where season in (${Prisma.join(seasonAliases.map((s) => Prisma.sql`${s}`))})
    `;

    return NextResponse.json({
      ok: true,
      mode: "refresh-yesterday",
      season,
      date,
      gamesFound: games.length,
      finishedGames: finishedGames.length,
      teamsFound: teamIds.size,
      playersTargeted: targetPlayerIds.length,
      targetMode,
      rotationPerTeam,
      rotationMinGp,
      processed,
      success,
      failed,
      rosterTeamsUpdated: rosterSync.updated,
      rosterRefresh: rosterRefreshResult,
      logsPlayersCoverage: Number(coverageRows[0]?.players ?? 0),
      logsMaxDate: coverageRows[0]?.max_date ?? null,
      playedGamesFetched:
        targetMode === "played"
          ? Math.max(
              0,
              gamesForScope.length - playedGameFetchFailures.length,
            )
          : undefined,
      playedGamesFailed:
        targetMode === "played" ? playedGameFetchFailures.length : undefined,
      durationMs: Date.now() - startedAt,
      details: includeDetails ? failedDetails : undefined,
    });
  } catch (err) {
    return NextResponse.json(
      {
        ok: false,
        error: err instanceof Error ? err.message : String(err),
        season,
        date,
      },
      { status: 500 },
    );
  }
}
