import { prisma } from "@/lib/prisma";

export type NbaPlayerRecord = {
  id: number;
  firstName: string | null;
  lastName: string | null;
  fullName: string;
  teamId: number | null;
  teamName: string | null;
  teamCode: string | null;
  position: string | null;
  jerseyNumber: string | null;
  age: number | null;
  height: string | null;
  weight: string | null;
  nationality: string | null;
  birthDate: string | null;
  isActive: boolean | null;
};

type NbaPlayerDbRow = {
  player_id: number;
  season: string;
  full_name: string;
  first_name: string | null;
  last_name: string | null;
  team_id: number | null;
  team_name: string | null;
  team_code: string | null;
  position: string | null;
  jersey_number: string | null;
  age: number | null;
  height: string | null;
  weight: string | null;
  nationality: string | null;
  birth_date: string | Date | null;
  is_active: boolean | null;
};

type UpsertNbaPlayersParams = {
  season: string;
  source?: string;
  players: NbaPlayerRecord[];
};

let playersTableInit: Promise<void> | null = null;

export function nbaSeasonAliases(season: string): string[] {
  const input = String(season || "").trim();
  const yearMatch = input.match(/(\d{4})/);
  const year = yearMatch ? Number(yearMatch[1]) : null;
  const span = Number.isFinite(year) ? `${year}-${(year as number) + 1}` : null;
  return Array.from(new Set([input, span, yearMatch?.[1] ?? null].filter(Boolean) as string[]));
}

export function normalizeNbaSeasonLabel(season: string): string {
  const aliases = nbaSeasonAliases(season);
  const span = aliases.find((s) => /^\d{4}-\d{4}$/.test(s));
  return span ?? aliases[0] ?? season;
}

function cleanText(value: unknown): string | null {
  if (value === null || value === undefined) return null;
  const str = String(value).trim();
  return str.length ? str : null;
}

function cleanInt(value: unknown): number | null {
  const n = typeof value === "number" ? value : Number(value);
  return Number.isFinite(n) ? Math.trunc(n) : null;
}

function cleanBool(value: unknown): boolean | null {
  if (typeof value === "boolean") return value;
  if (value === 1 || value === "1" || value === "true") return true;
  if (value === 0 || value === "0" || value === "false") return false;
  return null;
}

function normalizeSearchText(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function normalizePlayerForDb(player: NbaPlayerRecord): NbaPlayerRecord | null {
  const id = cleanInt(player.id);
  if (!id || id <= 0) return null;

  const firstName = cleanText(player.firstName);
  const lastName = cleanText(player.lastName);
  const fullFromParts = [firstName, lastName].filter(Boolean).join(" ").trim();
  const fullName = fullFromParts || cleanText(player.fullName) || `Player ${id}`;

  return {
    id,
    firstName,
    lastName,
    fullName,
    teamId: cleanInt(player.teamId),
    teamName: cleanText(player.teamName),
    teamCode: cleanText(player.teamCode),
    position: cleanText(player.position),
    jerseyNumber: cleanText(player.jerseyNumber),
    age: cleanInt(player.age),
    height: cleanText(player.height),
    weight: cleanText(player.weight),
    nationality: cleanText(player.nationality),
    birthDate: cleanText(player.birthDate),
    isActive: cleanBool(player.isActive),
  };
}

function mapDbRowToPlayer(row: NbaPlayerDbRow): NbaPlayerRecord {
  const birthDate =
    row.birth_date instanceof Date
      ? row.birth_date.toISOString().slice(0, 10)
      : cleanText(row.birth_date);

  return {
    id: row.player_id,
    firstName: row.first_name,
    lastName: row.last_name,
    fullName: row.full_name,
    teamId: row.team_id,
    teamName: row.team_name,
    teamCode: row.team_code,
    position: row.position,
    jerseyNumber: row.jersey_number,
    age: row.age,
    height: row.height,
    weight: row.weight,
    nationality: row.nationality,
    birthDate,
    isActive: row.is_active,
  };
}

export async function ensureNbaPlayersTable() {
  if (playersTableInit) return playersTableInit;
  playersTableInit = (async () => {
    try {
      await prisma.$executeRawUnsafe(`
        create table if not exists nba_players (
          id bigint generated by default as identity primary key,
          player_id integer not null,
          season text not null,
          full_name text not null,
          first_name text,
          last_name text,
          team_id integer,
          team_name text,
          team_code text,
          position text,
          jersey_number text,
          age integer,
          height text,
          weight text,
          nationality text,
          birth_date date,
          is_active boolean,
          search_name text not null default '',
          source text,
          created_at timestamptz default now(),
          updated_at timestamptz default now(),
          unique (player_id, season)
        );
      `);
      await prisma.$executeRawUnsafe(`
        create index if not exists nba_players_season_search_idx
        on nba_players (season, search_name);
      `);
      await prisma.$executeRawUnsafe(`
        create index if not exists nba_players_season_team_idx
        on nba_players (season, team_id);
      `);
    } catch {
      // ignore setup failures
    }
  })();
  return playersTableInit;
}

export async function upsertNbaPlayersForSeason({
  season,
  source = "api",
  players,
}: UpsertNbaPlayersParams): Promise<number> {
  if (!players.length) return 0;
  await ensureNbaPlayersTable();

  const deduped = new Map<number, NbaPlayerRecord>();
  for (const raw of players) {
    const normalized = normalizePlayerForDb(raw);
    if (!normalized) continue;
    deduped.set(normalized.id, normalized);
  }
  const rows = Array.from(deduped.values());
  if (!rows.length) return 0;
  const seasonKey = normalizeNbaSeasonLabel(season);

  const queries = rows.map((row) => {
    const first = cleanText(row.firstName);
    const last = cleanText(row.lastName);
    const full = cleanText(row.fullName) ?? [first, last].filter(Boolean).join(" ");
    const searchName = normalizeSearchText(
      [full, [first, last].filter(Boolean).join(" "), [last, first].filter(Boolean).join(" ")]
        .filter(Boolean)
        .join(" "),
    );
    const birthDate =
      row.birthDate && !Number.isNaN(Date.parse(row.birthDate))
        ? new Date(row.birthDate).toISOString().slice(0, 10)
        : null;
    return prisma.$executeRaw`
      insert into nba_players (
        player_id,
        season,
        full_name,
        first_name,
        last_name,
        team_id,
        team_name,
        team_code,
        position,
        jersey_number,
        age,
        height,
        weight,
        nationality,
        birth_date,
        is_active,
        search_name,
        source,
        updated_at
      ) values (
        ${row.id},
        ${seasonKey},
        ${full ?? `Player ${row.id}`},
        ${first},
        ${last},
        ${row.teamId},
        ${row.teamName},
        ${row.teamCode},
        ${row.position},
        ${row.jerseyNumber},
        ${row.age},
        ${row.height},
        ${row.weight},
        ${row.nationality},
        cast(${birthDate} as date),
        ${row.isActive},
        ${searchName},
        ${source},
        now()
      )
      on conflict (player_id, season)
      do update set
        full_name = excluded.full_name,
        first_name = excluded.first_name,
        last_name = excluded.last_name,
        team_id = excluded.team_id,
        team_name = excluded.team_name,
        team_code = excluded.team_code,
        position = excluded.position,
        jersey_number = excluded.jersey_number,
        age = excluded.age,
        height = excluded.height,
        weight = excluded.weight,
        nationality = excluded.nationality,
        birth_date = excluded.birth_date,
        is_active = excluded.is_active,
        search_name = excluded.search_name,
        source = excluded.source,
        updated_at = excluded.updated_at
    `;
  });

  const batchSize = 200;
  for (let i = 0; i < queries.length; i += batchSize) {
    await prisma.$transaction(queries.slice(i, i + batchSize));
  }
  return rows.length;
}

export async function readNbaPlayersFromDb(season: string): Promise<NbaPlayerRecord[]> {
  await ensureNbaPlayersTable();
  for (const alias of nbaSeasonAliases(season)) {
    try {
      const rows = await prisma.$queryRaw<NbaPlayerDbRow[]>`
        select
          player_id,
          season,
          full_name,
          first_name,
          last_name,
          team_id,
          team_name,
          team_code,
          position,
          jersey_number,
          age,
          height,
          weight,
          nationality,
          birth_date,
          is_active
        from nba_players
        where season = ${alias}
        order by full_name asc
      `;
      if (rows.length) return rows.map(mapDbRowToPlayer);
    } catch {
      // ignore alias failures and try next alias
    }
  }
  return [];
}

export async function readNbaPlayerByIdFromDb(
  season: string,
  playerId: number,
): Promise<NbaPlayerRecord | null> {
  await ensureNbaPlayersTable();
  for (const alias of nbaSeasonAliases(season)) {
    try {
      const rows = await prisma.$queryRaw<NbaPlayerDbRow[]>`
        select
          player_id,
          season,
          full_name,
          first_name,
          last_name,
          team_id,
          team_name,
          team_code,
          position,
          jersey_number,
          age,
          height,
          weight,
          nationality,
          birth_date,
          is_active
        from nba_players
        where season = ${alias}
          and player_id = ${playerId}
        limit 1
      `;
      if (rows.length) return mapDbRowToPlayer(rows[0]);
    } catch {
      // ignore alias failures and try next alias
    }
  }
  return null;
}

export async function readNbaPlayerIdsFromDb(season: string): Promise<number[]> {
  await ensureNbaPlayersTable();
  const ids = new Set<number>();
  for (const alias of nbaSeasonAliases(season)) {
    try {
      const rows = await prisma.$queryRaw<{ player_id: number }[]>`
        select player_id
        from nba_players
        where season = ${alias}
        order by player_id asc
      `;
      for (const row of rows) {
        const id = Number(row.player_id);
        if (Number.isFinite(id) && id > 0) ids.add(id);
      }
    } catch {
      // ignore alias failures and continue
    }
  }
  return Array.from(ids.values()).sort((a, b) => a - b);
}
