create table if not exists nba_players (
  id bigint generated by default as identity primary key,
  player_id integer not null,
  season text not null,
  full_name text not null,
  first_name text,
  last_name text,
  team_id integer,
  team_name text,
  team_code text,
  position text,
  jersey_number text,
  age integer,
  height text,
  weight text,
  nationality text,
  birth_date date,
  is_active boolean,
  search_name text not null default '',
  source text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (player_id, season)
);

create index if not exists nba_players_season_search_idx
  on nba_players (season, search_name);

create index if not exists nba_players_season_team_idx
  on nba_players (season, team_id);
