import { prisma } from "@/lib/prisma";

export type AuthUserPublic = {
  id: number;
  email: string;
  displayName: string | null;
  createdAt: string | null;
};

type AuthUserRow = {
  id: number | bigint | string;
  email: string;
  display_name: string | null;
  password_hash: string;
  created_at: Date | string | null;
};

type SessionRow = {
  id: number | bigint | string;
  user_id: number | bigint | string;
  token_hash: string;
  expires_at: Date | string;
  revoked_at: Date | string | null;
};

type SessionWithUserRow = {
  session_id: number | bigint | string;
  expires_at: Date | string;
  revoked_at: Date | string | null;
  user_id: number | bigint | string;
  email: string;
  display_name: string | null;
  created_at: Date | string | null;
  is_active: boolean | null;
};

let authTablesInit: Promise<void> | null = null;

function toInt(value: number | bigint | string): number {
  const num =
    typeof value === "number"
      ? value
      : typeof value === "bigint"
      ? Number(value)
      : Number(value);
  return Number.isFinite(num) ? Math.trunc(num) : 0;
}

function toIso(value: Date | string | null): string | null {
  if (!value) return null;
  const date = value instanceof Date ? value : new Date(value);
  return Number.isNaN(date.getTime()) ? null : date.toISOString();
}

function mapUserPublic(row: {
  id: number | bigint | string;
  email: string;
  display_name: string | null;
  created_at: Date | string | null;
}): AuthUserPublic {
  return {
    id: toInt(row.id),
    email: row.email,
    displayName: row.display_name,
    createdAt: toIso(row.created_at),
  };
}

export async function ensureAuthTables(): Promise<void> {
  if (authTablesInit) return authTablesInit;
  authTablesInit = (async () => {
    await prisma.$executeRawUnsafe(`
      create table if not exists app_users (
        id bigint generated by default as identity primary key,
        email text not null unique,
        password_hash text not null,
        display_name text,
        is_active boolean not null default true,
        last_login_at timestamptz,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now()
      );
    `);

    await prisma.$executeRawUnsafe(`
      create table if not exists app_user_sessions (
        id bigint generated by default as identity primary key,
        user_id bigint not null references app_users(id) on delete cascade,
        token_hash text not null unique,
        ip text,
        user_agent text,
        expires_at timestamptz not null,
        revoked_at timestamptz,
        created_at timestamptz not null default now()
      );
    `);

    await prisma.$executeRawUnsafe(`
      create index if not exists app_user_sessions_user_id_idx
      on app_user_sessions (user_id);
    `);

    await prisma.$executeRawUnsafe(`
      create index if not exists app_user_sessions_expires_idx
      on app_user_sessions (expires_at);
    `);
  })();
  return authTablesInit;
}

export async function findAuthUserByEmail(
  email: string,
): Promise<(AuthUserPublic & { passwordHash: string }) | null> {
  await ensureAuthTables();
  const rows = await prisma.$queryRaw<AuthUserRow[]>`
    select id, email, display_name, password_hash, created_at
    from app_users
    where email = ${email}
    limit 1
  `;
  if (!rows.length) return null;
  const row = rows[0];
  return {
    ...mapUserPublic(row),
    passwordHash: row.password_hash,
  };
}

export async function findAuthUserById(
  userId: number,
): Promise<(AuthUserPublic & { passwordHash: string }) | null> {
  await ensureAuthTables();
  const rows = await prisma.$queryRaw<AuthUserRow[]>`
    select id, email, display_name, password_hash, created_at
    from app_users
    where id = ${userId}
    limit 1
  `;
  if (!rows.length) return null;
  const row = rows[0];
  return {
    ...mapUserPublic(row),
    passwordHash: row.password_hash,
  };
}

export async function createAuthUser(params: {
  email: string;
  displayName: string | null;
  passwordHash: string;
}): Promise<AuthUserPublic> {
  await ensureAuthTables();
  const rows = await prisma.$queryRaw<AuthUserRow[]>`
    insert into app_users (email, display_name, password_hash, created_at, updated_at)
    values (${params.email}, ${params.displayName}, ${params.passwordHash}, now(), now())
    returning id, email, display_name, password_hash, created_at
  `;
  return mapUserPublic(rows[0]);
}

export async function createAuthSession(params: {
  userId: number;
  tokenHash: string;
  expiresAt: Date;
  ip: string | null;
  userAgent: string | null;
}): Promise<{ id: number; expiresAt: string | null }> {
  await ensureAuthTables();
  const rows = await prisma.$queryRaw<SessionRow[]>`
    insert into app_user_sessions (user_id, token_hash, expires_at, ip, user_agent)
    values (${params.userId}, ${params.tokenHash}, ${params.expiresAt}, ${params.ip}, ${params.userAgent})
    returning id, user_id, token_hash, expires_at, revoked_at
  `;
  const row = rows[0];
  return { id: toInt(row.id), expiresAt: toIso(row.expires_at) };
}

export async function revokeAuthSessionByTokenHash(
  tokenHash: string,
): Promise<void> {
  await ensureAuthTables();
  await prisma.$executeRaw`
    update app_user_sessions
    set revoked_at = now()
    where token_hash = ${tokenHash} and revoked_at is null
  `;
}

export async function touchAuthUserLastLogin(userId: number): Promise<void> {
  await ensureAuthTables();
  await prisma.$executeRaw`
    update app_users
    set last_login_at = now(), updated_at = now()
    where id = ${userId}
  `;
}

export async function updateAuthUserProfile(params: {
  userId: number;
  email?: string | null;
  displayName?: string | null;
}): Promise<AuthUserPublic | null> {
  await ensureAuthTables();
  const rows = await prisma.$queryRaw<AuthUserRow[]>`
    update app_users
    set
      email = coalesce(${params.email ?? null}, email),
      display_name = coalesce(${params.displayName ?? null}, display_name),
      updated_at = now()
    where id = ${params.userId}
    returning id, email, display_name, password_hash, created_at
  `;
  if (!rows.length) return null;
  return mapUserPublic(rows[0]);
}

export async function updateAuthUserPassword(
  userId: number,
  passwordHash: string,
): Promise<void> {
  await ensureAuthTables();
  await prisma.$executeRaw`
    update app_users
    set password_hash = ${passwordHash}, updated_at = now()
    where id = ${userId}
  `;
}

export async function revokeAllAuthSessionsForUser(userId: number): Promise<void> {
  await ensureAuthTables();
  await prisma.$executeRaw`
    update app_user_sessions
    set revoked_at = now()
    where user_id = ${userId} and revoked_at is null
  `;
}

export async function deleteAuthUserById(userId: number): Promise<void> {
  await ensureAuthTables();
  await prisma.$executeRaw`
    delete from app_users
    where id = ${userId}
  `;
}

export async function findActiveSessionWithUser(
  tokenHash: string,
): Promise<{ user: AuthUserPublic; expiresAt: string | null } | null> {
  await ensureAuthTables();
  const rows = await prisma.$queryRaw<SessionWithUserRow[]>`
    select
      s.id as session_id,
      s.expires_at,
      s.revoked_at,
      u.id as user_id,
      u.email,
      u.display_name,
      u.created_at,
      u.is_active
    from app_user_sessions s
    inner join app_users u on u.id = s.user_id
    where s.token_hash = ${tokenHash}
    limit 1
  `;

  if (!rows.length) return null;
  const row = rows[0];
  const expiresAt = row.expires_at instanceof Date ? row.expires_at : new Date(row.expires_at);
  const isExpired = Number.isNaN(expiresAt.getTime()) || expiresAt.getTime() <= Date.now();
  const isRevoked = Boolean(row.revoked_at);
  const isActive = row.is_active !== false;
  if (isExpired || isRevoked || !isActive) return null;

  return {
    user: mapUserPublic({
      id: row.user_id,
      email: row.email,
      display_name: row.display_name,
      created_at: row.created_at,
    }),
    expiresAt: toIso(row.expires_at),
  };
}
